[package]
name = "dsl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom="7.1.1"
chrono="0.4.19"
dateparser="0.1.6"
duration-str="0.3.9"