[package]
name = "quarry-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion="7.0.0"
arrow-flight="9.1.0"
tokio = {version="1.17.0", features = ["rt-multi-thread"] }
log="0.4.14"
spargebra = "0.2.0-rc.1"
reqwest="0.11.10"