name: All tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Upgrade rust and pull oxigraph image
      run: |
        rustup update
        docker pull oxigraph/oxigraph:v0.3.2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

    - name: Build
      run: cargo build --verbose --all
    - name: Run rust tests
      run: cargo test --verbose --all

    - name: Install dependencies
      run: |
        pwd
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install maturin
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./py-mapper

    - name: Build install package
      run: |
        pwd
        source .venv/bin/activate
        cwd
        maturin develop
      working-directory: ./py-mapper

    - name: pytest
      run: |
        cd tests
        pytest
      working-directory: ./py-mapper/tests
