name: Python mapper tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./py_otit_swt_mapper

    - name: Set up nightly rust
      run: |
        rustup toolchain install nightly
        rustup default nightly

    - name: Build install package
      run: |
        source .venv/bin/activate
        maturin develop
      working-directory: ./py_otit_swt_mapper

    - name: pytest
      run: |
        source ../.venv/bin/activate
        pytest
      working-directory: ./py_otit_swt_mapper/tests
