name: Python query tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install pytest maturin docker requests sparqlwrapper
      working-directory: ./py_otit_swt_query

    - name: Build install package
      run: |
        source .venv/bin/activate
        maturin develop
      working-directory: ./py_otit_swt_query

    - name: pytest
      run: |
        source ../.venv/bin/activate
        pytest
      working-directory: ./py_otit_swt_query/tests
