name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install pytest maturin
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ./py-mapper

    - name: Build install package
      run: |
        source .venv/bin/activate
        maturin develop
      working-directory: ./py-mapper

    - name: pytest
      run: |
        pytest
      working-directory: ./py-mapper/tests
