name: Release tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create venv
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install maturin
      working-directory: .

    - name: Build query wheels
      run: |
        source ../.venv/bin/activate
        maturin build
      working-directory: ./py_otit_swt_query

    - name: Build mapper wheels
      run: |
        source ../.venv/bin/activate
        maturin build
      working-directory: ./py_otit_swt_mapper

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./py-query/target/wheels/*.whl
          ./py-mapper/target/wheels/*.whl